name: "video"
host: "127.0.0.1"
port: 9704
user-server:
  host: "127.0.0.1"
  port: 9801
  name: "grpc-user-server"
video-server:
  host: "127.0.0.1"
  port: 9802
  name: "grpc-video-server"
rabbit-server:
  host: "127.0.0.1"
  port: 5672
  name: "rabbitmq-server"
  queue_suffix: ""