apiVersion: v1
kind: Service
metadata:
  name: message-web-server
  labels:
    app: qvbilam-http
spec:
  selector:
    app: message-web
  ports:
    - name: http-server-user
      protocol: TCP
      port: 9704
      targetPort: 9501
  type: NodePort